all: iscnothreads

iscnothreads:
	$(CC)  -I../../../../ -I../../../../lib/isc/nothreads/include -I../../../../lib/isc/nothreads/../unix/include -I../../../../lib/export/isc/include -I../include -I../../../../lib/isc/nothreads/../include -I../../../../lib/isc/nothreads/..     -g -O0  -W -Wall -Wmissing-prototypes -Wcast-qual -Wwrite-strings -Wformat -Wpointer-arith -fno-strict-aliasing  -c ../../../../lib/isc/nothreads/thread.c

clean:
	rm -f *.o

