all: common

common:
	rm -Rf .deps
	mkdir .deps
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT alloc.o -MD -MP -MF .deps/alloc.Tpo -c -o alloc.o alloc.c
	mv -f .deps/alloc.Tpo .deps/alloc.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT bpf.o -MD -MP -MF .deps/bpf.Tpo -c -o bpf.o bpf.c
	mv -f .deps/bpf.Tpo .deps/bpf.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT comapi.o -MD -MP -MF .deps/comapi.Tpo -c -o comapi.o comapi.c
	mv -f .deps/comapi.Tpo .deps/comapi.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT conflex.o -MD -MP -MF .deps/conflex.Tpo -c -o conflex.o conflex.c
	mv -f .deps/conflex.Tpo .deps/conflex.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT ctrace.o -MD -MP -MF .deps/ctrace.Tpo -c -o ctrace.o ctrace.c
	mv -f .deps/ctrace.Tpo .deps/ctrace.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT discover.o -MD -MP -MF .deps/discover.Tpo -c -o discover.o discover.c
	mv -f .deps/discover.Tpo .deps/discover.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT dispatch.o -MD -MP -MF .deps/dispatch.Tpo -c -o dispatch.o dispatch.c
	mv -f .deps/dispatch.Tpo .deps/dispatch.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT dlpi.o -MD -MP -MF .deps/dlpi.Tpo -c -o dlpi.o dlpi.c
	mv -f .deps/dlpi.Tpo .deps/dlpi.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT dns.o -MD -MP -MF .deps/dns.Tpo -c -o dns.o dns.c
	mv -f .deps/dns.Tpo .deps/dns.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT ethernet.o -MD -MP -MF .deps/ethernet.Tpo -c -o ethernet.o ethernet.c
	mv -f .deps/ethernet.Tpo .deps/ethernet.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT execute.o -MD -MP -MF .deps/execute.Tpo -c -o execute.o execute.c
	mv -f .deps/execute.Tpo .deps/execute.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT fddi.o -MD -MP -MF .deps/fddi.Tpo -c -o fddi.o fddi.c
	mv -f .deps/fddi.Tpo .deps/fddi.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT icmp.o -MD -MP -MF .deps/icmp.Tpo -c -o icmp.o icmp.c
	mv -f .deps/icmp.Tpo .deps/icmp.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT inet.o -MD -MP -MF .deps/inet.Tpo -c -o inet.o inet.c
	mv -f .deps/inet.Tpo .deps/inet.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT lpf.o -MD -MP -MF .deps/lpf.Tpo -c -o lpf.o lpf.c
	mv -f .deps/lpf.Tpo .deps/lpf.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT memory.o -MD -MP -MF .deps/memory.Tpo -c -o memory.o memory.c
	mv -f .deps/memory.Tpo .deps/memory.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT nit.o -MD -MP -MF .deps/nit.Tpo -c -o nit.o nit.c
	mv -f .deps/nit.Tpo .deps/nit.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT ns_name.o -MD -MP -MF .deps/ns_name.Tpo -c -o ns_name.o ns_name.c
	mv -f .deps/ns_name.Tpo .deps/ns_name.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT options.o -MD -MP -MF .deps/options.Tpo -c -o options.o options.c
	mv -f .deps/options.Tpo .deps/options.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT packet.o -MD -MP -MF .deps/packet.Tpo -c -o packet.o packet.c
	mv -f .deps/packet.Tpo .deps/packet.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT parse.o -MD -MP -MF .deps/parse.Tpo -c -o parse.o parse.c
	mv -f .deps/parse.Tpo .deps/parse.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT print.o -MD -MP -MF .deps/print.Tpo -c -o print.o print.c
	mv -f .deps/print.Tpo .deps/print.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT raw.o -MD -MP -MF .deps/raw.Tpo -c -o raw.o raw.c
	mv -f .deps/raw.Tpo .deps/raw.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT resolv.o -MD -MP -MF .deps/resolv.Tpo -c -o resolv.o resolv.c
	mv -f .deps/resolv.Tpo .deps/resolv.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT socket.o -MD -MP -MF .deps/socket.Tpo -c -o socket.o socket.c
	mv -f .deps/socket.Tpo .deps/socket.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT tables.o -MD -MP -MF .deps/tables.Tpo -c -o tables.o tables.c
	mv -f .deps/tables.Tpo .deps/tables.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT tr.o -MD -MP -MF .deps/tr.Tpo -c -o tr.o tr.c
	mv -f .deps/tr.Tpo .deps/tr.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT tree.o -MD -MP -MF .deps/tree.Tpo -c -o tree.o tree.c
	mv -f .deps/tree.Tpo .deps/tree.Po
	$(CC) -DHAVE_CONFIG_H -I. -I../includes  -I.. -DLOCALSTATEDIR='"/var"'   -g -O0  -Wall -Werror -fno-strict-aliasing -I../bind/include -MT upf.o -MD -MP -MF .deps/upf.Tpo -c -o upf.o upf.c
	mv -f .deps/upf.Tpo .deps/upf.Po
	rm -f libdhcp.a
	$(AR) cru libdhcp.a alloc.o bpf.o comapi.o conflex.o ctrace.o discover.o dispatch.o dlpi.o dns.o ethernet.o execute.o fddi.o icmp.o inet.o lpf.o memory.o nit.o ns_name.o options.o packet.o parse.o print.o raw.o resolv.o socket.o tables.o tr.o tree.o upf.o 
	$(RANLIB) libdhcp.a

clean:
	rm -Rf .deps
	rm -f *.o
	rm -f *.a
